import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "@/components/ui/common/app-header";
import AppFooter from "@/components/ui/common/app-footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-background text-foreground`}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
