import type { Metadata } from "next";
import "./globals.css";
import Script from "next/dist/client/script";
import AppHeader from "@/components/common/app-header";
import AppFooter from "@/components/common/app-footer";
import { Toaster } from "@/components/ui/sonner";

const TAWK_URL = process.env.NEXT_PUBLIC_TAWK_URL;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col bg-background text-foreground `}>
        <AppHeader />
        {/* <main className="flex-1 flex flex-col h-full"> */}
          {children}
          {/* </main> */}
        <AppFooter />
        <Toaster />

        {/* Tawk Chat Script */}
        <Script
          id="tawk-to"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),
                s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='${TAWK_URL}';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
